export enum SingUpTypes {
  ADD_USER_INITIALS = '[AUTH] ADD_USER_INITIAL',
  ADD_USER_PHONE = '[AUTH] ADD USER PHONE',
  ADD_USER_CODE = '[AUTH] ADD USER CODE',

  START = '[AUTH] SING UP START',
  SUCCESS = '[AUTH] SING UP SUCCESS',
  FAILURE = '[AUTH] SING UP FAILURE ',
}
