import {SubmittingAction, UserCodeSuccessfulConfirm} from "../action/sign-up.action";

export enum SingUpTypes {
  ADD_USER_INITIALS = '[AUTH] ADD_USER_INITIAL',
  ADD_USER_PHONE = '[AUTH] ADD USER PHONE',
  SEND_USER_PHONE = '[AUTH] SEND USER PHONE',
  CODE_SUCCESSFUL_CONFIRM = '[AUTH] CODE SUCCESSFUL CONFIRM',
  SMS_ENDOWED = '[AUTH] SMS ENDOWED',
  ADD_USER_AVATAR = '[AUTH] ADD USER AVATAR',

  ADD_USER_CODE = '[AUTH] ADD USER CODE',
  BACKEND_ERROR = '[AUTH]  BACKEND ERROR',


  START = '[AUTH] SING UP START',

}
