export enum ChatTypes {
    GET_CONVERSATION='[Chat] GET USER CONVERSATION',
    GET_CONVERSATION_SUCCESS='[Chat] GET CONVERSATION SUCCESS',
    FEILURE_CONVERSATION='[Chat] FEILURE CONVERSATION',
  }
  